//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Deliverable19_Lab20_CoffeeShop_Init.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDesc { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> price { get; set; }
        public string imgName { get; set; }
    }
}
